import type { CoreCatalogEntry } from "./catalogTypes";

export const coreCatalog = [
  {
    "id": "tag_long_hair",
    "tag": "long hair",
    "label": "long hair",
    "koreanLabel": "긴 머리",
    "productCategory": "appearance",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Hairstyle & Color",
    "count": 4677240,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_short_hair",
    "tag": "short hair",
    "label": "short hair",
    "koreanLabel": "짧은 머리",
    "productCategory": "appearance",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Hairstyle & Color",
    "count": 2413535,
    "aliases": [],
    "priority": 94,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_blue_eyes",
    "tag": "blue eyes",
    "label": "blue eyes",
    "koreanLabel": "파란 눈",
    "productCategory": "appearance",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Eye Traits",
    "count": 1887667,
    "aliases": [],
    "priority": 92,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_brown_hair",
    "tag": "brown hair",
    "label": "brown hair",
    "koreanLabel": "갈색 머리",
    "productCategory": "appearance",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Hairstyle & Color",
    "count": 1628832,
    "aliases": [],
    "priority": 86,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_blonde_hair",
    "tag": "blonde hair",
    "label": "blonde hair",
    "koreanLabel": "금발 머리",
    "productCategory": "appearance",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Hairstyle & Color",
    "count": 1660569,
    "aliases": [],
    "priority": 84,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_twintails",
    "tag": "twintails",
    "label": "twintails",
    "koreanLabel": "트윈테일",
    "productCategory": "appearance",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Hairstyle & Color",
    "count": 961681,
    "aliases": [],
    "priority": 84,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_simple_background",
    "tag": "simple background",
    "label": "simple background",
    "koreanLabel": "단순한 배경",
    "productCategory": "background",
    "sourceMajorCategory": "Backgrounds",
    "sourceMinorCategory": "Solid & Abstract",
    "count": 1993334,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_indoors",
    "tag": "indoors",
    "label": "indoors",
    "koreanLabel": "실내",
    "productCategory": "background",
    "sourceMajorCategory": "Backgrounds",
    "sourceMinorCategory": "Indoor Environment",
    "count": 397504,
    "aliases": [],
    "priority": 95,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_outdoors",
    "tag": "outdoors",
    "label": "outdoors",
    "koreanLabel": "야외",
    "productCategory": "background",
    "sourceMajorCategory": "Backgrounds",
    "sourceMinorCategory": "Outdoor Environment",
    "count": 581066,
    "aliases": [
      "outdoor"
    ],
    "priority": 94,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_white_background",
    "tag": "white background",
    "label": "white background",
    "koreanLabel": "흰색 배경",
    "productCategory": "background",
    "sourceMajorCategory": "Backgrounds",
    "sourceMinorCategory": "Solid & Abstract",
    "count": 1649984,
    "aliases": [],
    "priority": 92,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_classroom",
    "tag": "classroom",
    "label": "classroom",
    "koreanLabel": "교실",
    "productCategory": "background",
    "sourceMajorCategory": "Backgrounds",
    "sourceMinorCategory": "Indoor Environment",
    "count": 19840,
    "aliases": [],
    "priority": 84,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_bedroom",
    "tag": "bedroom",
    "label": "bedroom",
    "koreanLabel": "침실",
    "productCategory": "background",
    "sourceMajorCategory": "Backgrounds",
    "sourceMinorCategory": "Indoor Environment",
    "count": 15335,
    "aliases": [],
    "priority": 82,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_transparent_background",
    "tag": "transparent background",
    "label": "transparent background",
    "koreanLabel": "투명 배경",
    "productCategory": "background",
    "sourceMajorCategory": "Backgrounds",
    "sourceMinorCategory": "Solid & Abstract",
    "count": 94123,
    "aliases": [],
    "priority": 80,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_sky",
    "tag": "sky",
    "label": "sky",
    "koreanLabel": "하늘",
    "productCategory": "background",
    "sourceMajorCategory": "Backgrounds",
    "sourceMinorCategory": "Natural Environment",
    "count": 467698,
    "aliases": [],
    "priority": 78,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_best_quality",
    "tag": "best quality",
    "label": "best quality",
    "koreanLabel": "",
    "productCategory": "custom_main",
    "sourceMajorCategory": "Manual",
    "sourceMinorCategory": "Override",
    "count": 0,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_masterpiece",
    "tag": "masterpiece",
    "label": "masterpiece",
    "koreanLabel": "",
    "productCategory": "custom_main",
    "sourceMajorCategory": "Manual",
    "sourceMinorCategory": "Override",
    "count": 0,
    "aliases": [],
    "priority": 96,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_highres",
    "tag": "highres",
    "label": "highres",
    "koreanLabel": "고해상도",
    "productCategory": "custom_main",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Quality & Resolution",
    "count": 5763262,
    "aliases": [
      "high resolution",
      "high res",
      "hires"
    ],
    "priority": 92,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_detailed",
    "tag": "detailed",
    "label": "detailed",
    "koreanLabel": "",
    "productCategory": "custom_main",
    "sourceMajorCategory": "Manual",
    "sourceMinorCategory": "Override",
    "count": 0,
    "aliases": [],
    "priority": 86,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_lowres",
    "tag": "lowres",
    "label": "lowres",
    "koreanLabel": "저해상도",
    "productCategory": "custom_negative",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Quality & Resolution",
    "count": 97617,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "negative",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_bad_anatomy",
    "tag": "bad anatomy",
    "label": "bad anatomy",
    "koreanLabel": "잘못된 인체 구조",
    "productCategory": "custom_negative",
    "sourceMajorCategory": "Other",
    "sourceMinorCategory": "Other",
    "count": 16592,
    "aliases": [],
    "priority": 98,
    "defaultVisible": true,
    "target": "negative",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_bad_hands",
    "tag": "bad hands",
    "label": "bad hands",
    "koreanLabel": "잘못 그린 손",
    "productCategory": "custom_negative",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Quality & Resolution",
    "count": 2971,
    "aliases": [],
    "priority": 96,
    "defaultVisible": true,
    "target": "negative",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_text",
    "tag": "text",
    "label": "text",
    "koreanLabel": "",
    "productCategory": "custom_negative",
    "sourceMajorCategory": "Manual",
    "sourceMinorCategory": "Override",
    "count": 0,
    "aliases": [],
    "priority": 88,
    "defaultVisible": true,
    "target": "negative",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_watermark",
    "tag": "watermark",
    "label": "watermark",
    "koreanLabel": "워터마크",
    "productCategory": "custom_negative",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Source Marking",
    "count": 142485,
    "aliases": [],
    "priority": 86,
    "defaultVisible": true,
    "target": "negative",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_blurry",
    "tag": "blurry",
    "label": "blurry",
    "koreanLabel": "흐릿함",
    "productCategory": "custom_negative",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Camera & Rendering Techniques",
    "count": 245072,
    "aliases": [],
    "priority": 84,
    "defaultVisible": true,
    "target": "negative",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_smile",
    "tag": "smile",
    "label": "smile",
    "koreanLabel": "미소",
    "productCategory": "expression",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "State & Emotion",
    "count": 3103697,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_open_mouth",
    "tag": "open mouth",
    "label": "open mouth",
    "koreanLabel": "벌린 입",
    "productCategory": "expression",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "State & Emotion",
    "count": 2563148,
    "aliases": [],
    "priority": 94,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_blush",
    "tag": "blush",
    "label": "blush",
    "koreanLabel": "홍조",
    "productCategory": "expression",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "State & Emotion",
    "count": 3145333,
    "aliases": [],
    "priority": 92,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_serious",
    "tag": "serious",
    "label": "serious",
    "koreanLabel": "진지함",
    "productCategory": "expression",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "State & Emotion",
    "count": 30482,
    "aliases": [],
    "priority": 84,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_crying",
    "tag": "crying",
    "label": "crying",
    "koreanLabel": "우는",
    "productCategory": "expression",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "State & Emotion",
    "count": 83320,
    "aliases": [],
    "priority": 78,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_angry",
    "tag": "angry",
    "label": "angry",
    "koreanLabel": "화남",
    "productCategory": "expression",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "State & Emotion",
    "count": 47168,
    "aliases": [],
    "priority": 76,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_looking_at_viewer",
    "tag": "looking at viewer",
    "label": "looking at viewer",
    "koreanLabel": "시선이 이쪽을 향함",
    "productCategory": "framing",
    "sourceMajorCategory": "Pose",
    "sourceMinorCategory": "Partial Pose",
    "count": 3591177,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_upper_body",
    "tag": "upper body",
    "label": "upper body",
    "koreanLabel": "상반신",
    "productCategory": "framing",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Composition & Angle",
    "count": 846746,
    "aliases": [],
    "priority": 92,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_full_body",
    "tag": "full body",
    "label": "full body",
    "koreanLabel": "전신",
    "productCategory": "framing",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Composition & Angle",
    "count": 895719,
    "aliases": [],
    "priority": 90,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_cowboy_shot",
    "tag": "cowboy shot",
    "label": "cowboy shot",
    "koreanLabel": "카우보이 샷",
    "productCategory": "framing",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Composition & Angle",
    "count": 612101,
    "aliases": [],
    "priority": 88,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_looking_away",
    "tag": "looking away",
    "label": "looking away",
    "koreanLabel": "",
    "productCategory": "framing",
    "sourceMajorCategory": "Manual",
    "sourceMinorCategory": "Override",
    "count": 0,
    "aliases": [],
    "priority": 86,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_close_up",
    "tag": "close-up",
    "label": "close-up",
    "koreanLabel": "클로즈업",
    "productCategory": "framing",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Composition & Angle",
    "count": 49406,
    "aliases": [],
    "priority": 82,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_from_side",
    "tag": "from side",
    "label": "from side",
    "koreanLabel": "옆에서 본 모습",
    "productCategory": "framing",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Composition & Angle",
    "count": 241313,
    "aliases": [],
    "priority": 76,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_1girl",
    "tag": "1girl",
    "label": "1girl",
    "koreanLabel": "여성 1명",
    "productCategory": "headcount",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Headcount & Relationship",
    "count": 6421189,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_solo",
    "tag": "solo",
    "label": "solo",
    "koreanLabel": "솔로",
    "productCategory": "headcount",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Headcount & Relationship",
    "count": 5341029,
    "aliases": [],
    "priority": 98,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_2girls",
    "tag": "2girls",
    "label": "2girls",
    "koreanLabel": "여성 2명",
    "productCategory": "headcount",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Headcount & Relationship",
    "count": 1095993,
    "aliases": [],
    "priority": 95,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_3girls",
    "tag": "3girls",
    "label": "3girls",
    "koreanLabel": "3명의 소녀",
    "productCategory": "headcount",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Headcount & Relationship",
    "count": 258978,
    "aliases": [],
    "priority": 90,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_1boy",
    "tag": "1boy",
    "label": "1boy",
    "koreanLabel": "남성 1명",
    "productCategory": "headcount",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Headcount & Relationship",
    "count": 1534656,
    "aliases": [],
    "priority": 88,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_solo_focus",
    "tag": "solo focus",
    "label": "solo focus",
    "koreanLabel": "솔로 포커스",
    "productCategory": "headcount",
    "sourceMajorCategory": "Image Composition",
    "sourceMinorCategory": "Focus",
    "count": 381244,
    "aliases": [],
    "priority": 86,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_2boys",
    "tag": "2boys",
    "label": "2boys",
    "koreanLabel": "남성 2명",
    "productCategory": "headcount",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Headcount & Relationship",
    "count": 332960,
    "aliases": [],
    "priority": 82,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_multiple_girls",
    "tag": "multiple girls",
    "label": "multiple girls",
    "koreanLabel": "다수의 여성",
    "productCategory": "headcount",
    "sourceMajorCategory": "Character",
    "sourceMinorCategory": "Headcount & Relationship",
    "count": 1638046,
    "aliases": [],
    "priority": 72,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_school_uniform",
    "tag": "school uniform",
    "label": "school uniform",
    "koreanLabel": "교복",
    "productCategory": "outfit",
    "sourceMajorCategory": "Clothing and Accessories",
    "sourceMinorCategory": "Costume",
    "count": 841569,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_dress",
    "tag": "dress",
    "label": "dress",
    "koreanLabel": "드레스",
    "productCategory": "outfit",
    "sourceMajorCategory": "Clothing and Accessories",
    "sourceMinorCategory": "Dress",
    "count": 1409522,
    "aliases": [],
    "priority": 92,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_shirt",
    "tag": "shirt",
    "label": "shirt",
    "koreanLabel": "셔츠",
    "productCategory": "outfit",
    "sourceMajorCategory": "Clothing and Accessories",
    "sourceMinorCategory": "Shirts and Topwear",
    "count": 2015072,
    "aliases": [],
    "priority": 86,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_skirt",
    "tag": "skirt",
    "label": "skirt",
    "koreanLabel": "스커트",
    "productCategory": "outfit",
    "sourceMajorCategory": "Clothing and Accessories",
    "sourceMinorCategory": "Pants and Bottomwear",
    "count": 1665110,
    "aliases": [],
    "priority": 84,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_jacket",
    "tag": "jacket",
    "label": "jacket",
    "koreanLabel": "재킷",
    "productCategory": "outfit",
    "sourceMajorCategory": "Clothing and Accessories",
    "sourceMinorCategory": "Shirts and Topwear",
    "count": 1040132,
    "aliases": [],
    "priority": 78,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_hat",
    "tag": "hat",
    "label": "hat",
    "koreanLabel": "모자",
    "productCategory": "outfit",
    "sourceMajorCategory": "Clothing and Accessories",
    "sourceMinorCategory": "Headwear and Headgear",
    "count": 1291656,
    "aliases": [],
    "priority": 72,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_standing",
    "tag": "standing",
    "label": "standing",
    "koreanLabel": "서있음",
    "productCategory": "pose",
    "sourceMajorCategory": "Pose",
    "sourceMinorCategory": "Full Body Pose",
    "count": 980341,
    "aliases": [],
    "priority": 100,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_sitting",
    "tag": "sitting",
    "label": "sitting",
    "koreanLabel": "앉아있음",
    "productCategory": "pose",
    "sourceMajorCategory": "Pose",
    "sourceMinorCategory": "Full Body Pose",
    "count": 1009301,
    "aliases": [],
    "priority": 96,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_lying",
    "tag": "lying",
    "label": "lying",
    "koreanLabel": "누워있음",
    "productCategory": "pose",
    "sourceMajorCategory": "Pose",
    "sourceMinorCategory": "Full Body Pose",
    "count": 476751,
    "aliases": [],
    "priority": 86,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_kneeling",
    "tag": "kneeling",
    "label": "kneeling",
    "koreanLabel": "무릎 꿇기",
    "productCategory": "pose",
    "sourceMajorCategory": "Pose",
    "sourceMinorCategory": "Full Body Pose",
    "count": 126005,
    "aliases": [],
    "priority": 80,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_arms_up",
    "tag": "arms up",
    "label": "arms up",
    "koreanLabel": "양팔 들기",
    "productCategory": "pose",
    "sourceMajorCategory": "Pose",
    "sourceMinorCategory": "Full Body Pose",
    "count": 201178,
    "aliases": [],
    "priority": 78,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  },
  {
    "id": "tag_hand_on_hip",
    "tag": "hand on hip",
    "label": "hand on hip",
    "koreanLabel": "",
    "productCategory": "pose",
    "sourceMajorCategory": "Manual",
    "sourceMinorCategory": "Override",
    "count": 0,
    "aliases": [],
    "priority": 74,
    "defaultVisible": true,
    "target": "prompt",
    "reviewStatus": "accepted"
  }
] as const satisfies readonly CoreCatalogEntry[];

export const coreCatalogGeneratedBy = "scripts/catalog/build-core-catalog.mjs";
