import { useState } from 'react';
import { useMetadataState } from './hooks/useMetadataState';
import type { MetadataState } from './types/metadata';
import { buildCommentJson } from './model/buildCommentJson';
import { generatePngWithMetadata } from './encoding/pngEncoder';
import { dispatchPasteEvent } from './encoding/pasteDispatch';
import { useAutoGenerator } from './hooks/useAutoGenerator';
import type { QueueMode } from './types/preset';
import { ThemeProvider, useTheme } from './contexts/ThemeContext';
import PromptSection from './components/PromptSection';
import GenerationParams from './components/GenerationParams';
import CharacterCaptions from './components/CharacterCaptions';
import NegativePrompt from './components/NegativePrompt';
import AdvancedParams from './components/AdvancedParams';
import ApplyButton from './components/ApplyButton';
import PresetManager from './components/PresetManager';
import AutoGeneratePanel from './components/AutoGeneratePanel';
import ImportModal from './components/ImportModal';
import { parseNovelAIPng } from './utils/pngParser';
import { translateNovelAiMetadata } from './utils/metadataTranslator';

const CONTAINER_ID = 'nai-tag-builder-root';
function startDrag(clientX: number, clientY: number) {
  const el = document.getElementById(CONTAINER_ID) as HTMLElement | null;
  if (!el) return;

  const rect = el.getBoundingClientRect();
  el.style.right = '';
  el.style.left = rect.left + 'px';
  el.style.top = rect.top + 'px';

  let lx = clientX, ly = clientY;

  const move = (cx: number, cy: number) => {
    el.style.left = (parseFloat(el.style.left) + cx - lx) + 'px';
    el.style.top = (parseFloat(el.style.top) + cy - ly) + 'px';
    lx = cx;
    ly = cy;
  };

  const onMM = (e: MouseEvent) => move(e.clientX, e.clientY);
  const onTM = (e: TouchEvent) => { e.preventDefault(); move(e.touches[0].clientX, e.touches[0].clientY); };
  const up = () => {
    document.removeEventListener('mousemove', onMM);
    document.removeEventListener('mouseup', up);
    document.removeEventListener('touchmove', onTM);
    document.removeEventListener('touchend', up);
  };

  document.addEventListener('mousemove', onMM);
  document.addEventListener('mouseup', up);
  document.addEventListener('touchmove', onTM, { passive: false });
  document.addEventListener('touchend', up);
}

function AppContent() {
  const theme = useTheme();
  const [state, dispatch] = useMetadataState();
  const [isApplying, setIsApplying] = useState(false);
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [overlayWidth, setOverlayWidth] = useState(320);

  // Preset queue state
  const [queue, setQueue] = useState<string[]>([]);
  const [queueMode, setQueueMode] = useState<QueueMode>('progression');

  // Import Modal state
  const [pendingImport, setPendingImport] = useState<MetadataState | null>(null);

  // Drag and drop state
  const [isDragOver, setIsDragOver] = useState(false);

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'copy';
    setIsDragOver(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    if (e.currentTarget === e.target) {
      setIsDragOver(false);
    }
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);

    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      const file = e.dataTransfer.files[0];
      if (file.type === 'image/png') {
        try {
          const buffer = await file.arrayBuffer();
          const jsonMeta = parseNovelAIPng(buffer);
          if (jsonMeta) {
            const newState = translateNovelAiMetadata(jsonMeta);
            setPendingImport(newState);
          } else {
            alert('No NovelAI metadata found in this PNG.');
          }
        } catch (err) {
          console.error('Error parsing PNG:', err);
          alert('Failed to read PNG file.');
        }
      } else {
        alert('Please drop a valid .png file generated by NovelAI.');
      }
    }
  };

  // Auto-generation logic
  const {
    autoGenerate, setAutoGenerate,
    seedRule, setSeedRule,
    intervalSec, targetCount, targetMin, adjustStep, setAdjustStep,
    isLooping, loopCount,
    startLoop, stopLoop,
    handleIntervalChange, handleCountChange, handleMinChange, adjustValue,
  } = useAutoGenerator({ state, queue, queueMode });

  const handleClose = () => {
    stopLoop();
    document.getElementById(CONTAINER_ID)?.remove();
  };



  const handleApply = async () => {
    setIsApplying(true);
    try {
      const comment = buildCommentJson(state);
      const blob = await generatePngWithMetadata(comment);
      dispatchPasteEvent(blob, autoGenerate);
      setIsCollapsed(true);

      if (autoGenerate && Number(intervalSec) > 0 && Number(targetCount) > 0) {
        startLoop();
      }
    } catch (error) {
      console.error('Error applying preset:', error);
      alert('적용 중 오류가 발생했습니다.');
    } finally {
      setIsApplying(false);
    }
  };

  const startResize = (clientX: number) => {
    let startX = clientX;
    let startWidth = overlayWidth;

    const onMM = (e: MouseEvent) => {
      e.preventDefault();
      setOverlayWidth(Math.max(320, startWidth + (e.clientX - startX)));
    };

    const onTM = (e: TouchEvent) => {
      e.preventDefault();
      setOverlayWidth(Math.max(320, startWidth + (e.touches[0].clientX - startX)));
    };

    const up = () => {
      document.body.style.cursor = '';
      document.removeEventListener('mousemove', onMM);
      document.removeEventListener('mouseup', up);
      document.removeEventListener('touchmove', onTM);
      document.removeEventListener('touchend', up);
    };

    document.body.style.cursor = 'ew-resize';
    document.addEventListener('mousemove', onMM);
    document.addEventListener('mouseup', up);
    document.addEventListener('touchmove', onTM, { passive: false });
    document.addEventListener('touchend', up);
  };

  const headerBtnStyle: React.CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'none',
    border: 'none',
    padding: '0 2px',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '16px',
    lineHeight: 1,
  };


  return (
    <div
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
      style={{
        width: `${overlayWidth}px`,
        minWidth: '320px',
        maxWidth: '90vw',
        maxHeight: isCollapsed ? 'none' : '80vh',
        overflowY: isCollapsed ? 'visible' : 'auto',
        backgroundColor: theme.base,
        color: theme.text,
        borderRadius: '12px',
        boxShadow: '0 10px 30px rgba(0,0,0,0.6)',
        fontFamily: 'sans-serif',
        border: `1px solid ${theme.surface0}`,
        paddingBottom: isCollapsed ? '0' : '12px',
        position: 'relative', // Relative for absolute components like the handle
      }}
    >
      {/* Drag & Drop Overlay */}
      {isDragOver && (
        <div style={{
          position: 'absolute',
          top: 0, left: 0, right: 0, bottom: 0,
          backgroundColor: theme.mantle,
          opacity: 0.9,
          zIndex: 9999,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          borderRadius: '12px',
          border: `2px dashed ${theme.intensityHigh}`,
          color: theme.text,
        }}>
          <h2 style={{ fontSize: '18px', marginBottom: '8px' }}>Drop PNG Image Here</h2>
          <p style={{ fontSize: '12px', color: theme.subtext0 }}>Extract NovelAI metadata into Tag Builder</p>
        </div>
      )}

      {/* Right Edge Resize Handle */}
      {!isCollapsed && (
        <div
          onMouseDown={(e) => { e.preventDefault(); startResize(e.clientX); }}
          onTouchStart={(e) => { e.preventDefault(); startResize(e.touches[0].clientX); }}
          style={{
            position: 'absolute',
            top: 0,
            right: 0,
            width: '8px',
            height: '100%',
            cursor: 'ew-resize',
            zIndex: 10,
            touchAction: 'none'
          }}
        />
      )}

      {/* Header — drag handle */}
      <div
        onMouseDown={(e) => {
          if ((e.target as Element).closest('button')) return;
          if (e.button === 0) startDrag(e.clientX, e.clientY);
        }}
        onTouchStart={(e) => {
          if ((e.target as Element).closest('button')) return;
          startDrag(e.touches[0].clientX, e.touches[0].clientY);
        }}
        style={{
          backgroundColor: theme.crust,
          padding: '10px 16px',
          fontWeight: 'bold',
          fontSize: '14px',
          borderBottom: isCollapsed ? 'none' : `1px solid ${theme.surface0}`,
          marginBottom: isCollapsed ? '0' : '12px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          position: 'sticky',
          top: 0,
          zIndex: 1,
          cursor: 'grab',
          borderRadius: isCollapsed ? '12px' : '12px 12px 0 0',
          userSelect: 'none',
          touchAction: 'none',
        }}
      >
        <span>NAI Tag Builder v2.0</span>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          {isLooping && (
            <button
              onClick={stopLoop}
              title="반복 중지"
              style={{ ...headerBtnStyle, color: theme.yellow, display: 'flex', alignItems: 'center', gap: '4px' }}
            >
              <span style={{ fontSize: '10px' }}>({loopCount}/{targetCount})</span>
              &#9632;
            </button>
          )}
          {/* Collapse button */}
          <button
            onClick={() => setIsCollapsed(c => !c)}
            title={isCollapsed ? '펼치기' : '접기'}
            style={{ ...headerBtnStyle, color: theme.subtext0 }}
          >
            {isCollapsed ? '▲' : '▼'}
          </button>
          {/* Close button */}
          <button
            onClick={handleClose}
            title="닫기"
            style={{ ...headerBtnStyle, color: theme.red }}
          >
            &#10005;
          </button>
        </div>
      </div>

      {/* Body */}
      {!isCollapsed && (
        <div style={{ padding: '0 12px' }}>
          <PresetManager
            state={state}
            dispatch={dispatch}
            queue={queue}
            setQueue={setQueue}
            queueMode={queueMode}
            setQueueMode={setQueueMode}
            onImportRequest={setPendingImport}
          />
          <PromptSection value={state.basePrompt} dispatch={dispatch} />
          <GenerationParams state={state} dispatch={dispatch} />
          <CharacterCaptions characters={state.characters} dispatch={dispatch} />
          <NegativePrompt state={state} dispatch={dispatch} />
          <AdvancedParams state={state} dispatch={dispatch} />

          <AutoGeneratePanel
            autoGenerate={autoGenerate}
            setAutoGenerate={setAutoGenerate}
            seedRule={seedRule}
            setSeedRule={setSeedRule}
            adjustStep={adjustStep}
            setAdjustStep={setAdjustStep}
            intervalSec={intervalSec}
            handleIntervalChange={handleIntervalChange}
            targetCount={targetCount}
            handleCountChange={handleCountChange}
            targetMin={targetMin}
            handleMinChange={handleMinChange}
            adjustValue={adjustValue}
            queueLength={queue.length}
          />

          <ApplyButton isApplying={isApplying} onApply={handleApply} />
        </div>
      )}

      {pendingImport && (
        <ImportModal
          importedState={pendingImport}
          onConfirm={(partial) => {
            dispatch({ type: 'LOAD_PRESET', state: { ...state, ...partial } });
            setPendingImport(null);
          }}
          onCancel={() => setPendingImport(null)}
        />
      )}
    </div>
  );
}

export default function App() {
  return (
    <ThemeProvider>
      <AppContent />
    </ThemeProvider>
  );
}
